"""Add liked_tracks table

Revision ID: 1859552e116e
Revises: bd277c4ccf41
Create Date: 2026-05-12 10:44:06.169615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1859552e116e'
down_revision: Union[str, Sequence[str], None] = 'bd277c4ccf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('album_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('spotify_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liked_tracks_id'), 'liked_tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liked_tracks_id'), table_name='liked_tracks')
    op.drop_table('liked_tracks')
    # ### end Alembic commands ###
